### ISSUE TITLE
Selection and transform mode UX

### ISSUE THREAD

**Issue by lentsius-bark** [jarneson/godot-ply#33]
I've used plenty of 3D programs in my days yet wrapping my head around the current approach was rather difficult.
I've wondered about a possible improvement on it and thought about this one:

Q / Selection mode - turns off transform
WER / Transform gizmos - turn on transform

This way the tool wouldn't need to a toggle button for transform however it could be left for extra control.

**Comment by jarneson** [comment]
#41 should make this significantly better.

**Comment by jarneson** [comment]
Closing this with the landing of the new editor.
