### ISSUE TITLE
Provide a better UX for selecting loops

### ISSUE THREAD

**Issue by lentsius-bark** [jarneson/godot-ply#35]
As it stands, from the testing I've done on the 3.4 branch, the Loop with an icon for a horizontal one seems to select faces vertically and the opposite goes for the horizontal one.
I'd also recommend naming the buttons accordingly to their function and icon, ie "horizontal loop" and "vertical loop"

**Comment by jarneson** [comment]
They aren't actually inverted, they are somewhat arbitrary. I think long term I want to implement alt+click for loop selection though.

**Comment by lentsius-bark** [comment]
Gotcha, in that case let's wait for that :)
