### ISSUE TITLE
Allow "local" transformation of faces, edges and vertices

### ISSUE THREAD

**Issue by lentsius-bark** [jarneson/godot-ply#38]
Godot provides this little button to toggle moving object in their local space:
![image](https://user-images.githubusercontent.com/38346332/133845777-29b4efe8-6d78-4048-8a85-d510260d425e.png)

Allowing the users of Godot-ply to toggle the same mode, (perhaps they could even be linked?) would make the manipulation of shapes easier as well.

**Comment by jarneson** [comment]
Would local mean "positive y direction is the normal"?

**Comment by lentsius-bark** [comment]
It'd mean that the normal vector of the face, edge and vertex rotates the gizmo accordignly. Z + being 'forward'.

**Comment by jarneson** [comment]
This is getting implemented in #41
