### ISSUE TITLE
Raycast using the Geometry class

### ISSUE THREAD

**Issue by jarneson** [jarneson/godot-ply#42]
There's fully custom raycasting logic for selecting geometry: https://github.com/jarneson/godot-ply/blob/main/addons/ply/nodes/ply.gd#L141

We can just use [Geometry](https://docs.godotengine.org/en/stable/classes/class_geometry.html) from the engine.

Along the way this should make it easier to fix accidentally selecting things behind what we are trying to click

**Comment by fire** [comment]
Looking into it.

**Comment by fire** [comment]
From chat:

Convert code to ray casting to: 

* vert -> sphere
* edge -> cylinder
* face -> tris
