### ISSUE TITLE
Weird behavior when moving a face along its surface normal with grid snapping enabled

### ISSUE THREAD

**Issue by the-sink** [jarneson/godot-ply#64]
While attempting to move a face that isn't oriented flat (increments of 90 degrees) along its surface normal, it will not translate properly while grid snapping is being used (ctrl key held down).

**To Reproduce**
1. Create any shape with a face at a non-flat orientation (i.e. 45 degrees)
2. Select the face
3. Switch to Normal gizmo mode
4. Hold Ctrl and attempt to translate the face in the direction it is 'facing'

**Expected behavior**
The face is translated in the same manner as it is without grid snapping enabled (in the direction it is facing)

Video: https://cdn.discordapp.com/attachments/287420694931701760/999928164396568636/Godot_v3.4.4-stable_win64_2022-07-21_23-37-59.mp4

This occurs in both the published Godot 3.4 version as well as the latest version in the main branch.

**Comment by jarneson** [comment]
Thanks for the report @the-sink 

Fix is this one-liner: https://github.com/jarneson/godot-ply/commit/b75963fc523d26c971455d71eb5d1970557dc182#diff-cf6f85f38e23c21346408e65c6e8f8f4d925f678e94bd14e001a4cad07d9f062R624

should be easy to backport to 3.x if someone wants to.
