### ISSUE TITLE
Box Selection

### ISSUE THREAD

**Issue by jarneson** [jarneson/godot-ply#70]
**Is your feature request related to a problem? Please describe.**
I want to select multiple pieces of the same type of geometry at the same time

**Describe the solution you'd like**
Click and drag a box to select multiple elements

**Additional context**
It would be nice to have an x-ray mode toggle to select backfaces and such, but we'll defer on this for now.

- [x] Add box dragging to selector
- [x] Select Vertices
- [x] Select Faces
- [x] Select Edges
- [x] Select only visible geometry (e.g. clip on faces)

**Comment by fire** [comment]
Snapping has an implementation here https://github.com/jgillich/godot-snappy

**Comment by jarneson** [comment]
@fire An implementation of what?

**Comment by jarneson** [comment]
Ah yes, visual server could work, but verts don't render, however that's the simplest thing to implement.

**Comment by jarneson** [comment]
the godot source also has an implementation :)

**Comment by jarneson** [comment]
argh, renderingserver doesn't work unless each piece of geometry is its own visual instance. currently we have exactly three: wireframe, verts and selected faces
