### ISSUE TITLE
lack of compatibility with RC versions of Godot.

### ISSUE THREAD

**Issue by rcalastro** [jarneson/godot-ply#80]
**Describe the bug**
Current branch isn't compatible with most recent release candidates versions of Godot.

**To Reproduce**
1. Just open a project that works fine with beta2 in RC4 or RC5 versions.
2. Alternatively, try to install the addon and open the demo scene in these versions

**Expected behavior**
There will be 2 lines with error in plugin.gd file.
- func _handles(o: Variant) -> bool:
- func _edit(o: Variant) -> void:

"The function signature doesn't match the parent. Parent signature is _handles(Object)"...

**Additional context**
I checked the godot documentation (latest) and both "handle" and "edit" functions refers to Object instead a Variant.
https://docs.godotengine.org/en/latest/classes/class_editorplugin.html#class-editorplugin-method-handles

I tried the obvious solution, replacing Variant to Object, but didn't work.

This addon is awesome :)

**Comment by fire** [comment]
I tried updating the latest. Try testing.

**Comment by jarneson** [comment]
Closing as stale, seems to be mostly working in 4.1
