### ISSUE TITLE
Vertex and edge aiding displays no longer show on the viewport

### ISSUE THREAD

**Issue by Nevur** [jarneson/godot-ply#81]
**Describe the bug**
Viewport display for vertexes, edges, etc. no longer work, making working with the plugin considerably more difficult.
They can still be selected and manipulated, however.

**To Reproduce**
1. Create a MeshInstance and assign it a PlyEditor node.
2. Generate a primitive cube or load any other mesh.

**Expected behavior**
Vertexes and edges should display squares and lines respectively, but they no longer do.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10975006/227924324-876fbef8-aad1-45ca-a176-41fd0e6cedec.png)

**Additional context**
-

**Comment by MineBill** [comment]
See if #79 fixes it.

**Comment by Nevur** [comment]
Yes, this PR fixes it.

**Comment by fire** [comment]
I merged the pr in and it is still broken on Godot Engine 4.1,
